name = "HM Minecraft"
author = "Szymzal"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b44bd8ee1bbcee2d081b59d62192490be8c8e97d90325436b9c3fb2cc7497e16"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
