name = "HMMinecraft"
author = "Szymzal"
version = "1.2.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a98a291fe5567205b5ca9514e845d88976663f67c3ee84493ae8f80dd0669c34"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
