name = "HM Minecraft"
author = "Szymzal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8351e9bd6c3c1aa833faf50f1bd704911fde0bcbd70313bb8e3c8a422fd5e9d3"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
