name = "HM Minecraft"
author = "Szymzal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf90ebded53904255a1b0356ec4d87c679174c739420c166d7f880241cea2e5"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
