name = "HM Minecraft"
author = "Szymzal"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f66be88f092b6ec60787853bcc88e7e34b7f0fa24f01604cdff81b0653933e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
