name = "HM Minecraft"
author = "Szymzal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b7e1dcb753b0e66a9c3984f6a6f192878d46871fcba49bf82074d9a12e9df9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
