name = "HM Minecraft"
author = "Szymzal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5638fabfccf93fcdb4238fbc4ebda7e22e1cced2b8da710c75fe631bce818c18"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
