name = "TrueSurvival-S1"
author = "TerraFirmaGreg-Team, Szymzal"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfd2bec8a447561241fc04066d85a0612b97bf223c913a7a78e354bf984996fd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
