name = "TrueSurvival-S1"
author = "TerraFirmaGreg-Team, Szymzal"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1607e568d231048684c412dc4fc9b90aeedf47223bf24390e4f1cea0d1c2cd55"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
