name = "TrueSurvival-S1"
author = "TerraFirmaGreg-Team, Szymzal"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55b342423e0618c435decff19530640c867fa18441a59e04da4824f6ea277396"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
